runtime: python39

entrypoint: gunicorn -b :$PORT main:app

instance_class: F2

env_variables:
  PYTHONUNBUFFERED: 'true'

# Optional: increase memory limit if needed
resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10
